# Generated by import_vpn_full.py

resource "routeros_interface_sstp_client" "vpn__cn" {
  connect_to = "d4450c0e7cc6.sn.mynetname.net"
  user = "rchan"
  password = "password123"
  certificate = "none"
  add_default_route = "True"
  profile = "default-encryption"
}

resource "routeros_interface_sstp_client" "vpn__emd" {
  connect_to = "222.127.156.46"
  user = "rchan"
  password = "password123"
  certificate = "none"
  profile = "default-encryption"
}

resource "routeros_interface_sstp_client" "vpn__jj" {
  connect_to = "119.93.243.95"
  user = "rchan"
  password = "password123"
  certificate = "none"
  add_default_route = "True"
  profile = "default-encryption"
}

resource "routeros_interface_sstp_client" "vpn__z1" {
  connect_to = "122.3.109.208"
  user = "rchan"
  password = "password123"
  certificate = "none"
  add_default_route = "True"
  profile = "default-encryption"
}

resource "routeros_interface_sstp_client" "vpn_vx" {
  connect_to = "222.127.152.132"
  user = "rchan"
  password = "password123"
  certificate = "none"
  add_default_route = "True"
  profile = "default-encryption"
  comment = "222.127.208.224 ; 222.127.154.216 ; 222.127.152.132"
}

resource "routeros_interface_wireguard" "vpn__lc" {
  listen_port = "56474"
  private_key = "WH27fnS2kkzKAB2Gucz2cSHYA3ghcTSaIa8Z+6uHUko="
  mtu = "1420"
}

resource "routeros_interface_wireguard" "back_to_home_vpn" {
  listen_port = "43245"
  private_key = "aKrRBlL75C7jUIXirBFFkZeAm3RX204hrB0kcPTVE0Y="
  mtu = "1420"
  comment = "back-to-home-vpn"
}

resource "routeros_interface_wireguard_peer" "_7" {
  public_key = "E5/g2DcHEavoYt8ZEKsbx7XB7hGTLpdSrN8ts6j+ATE="
  allowed_address = "10.99.99.0/24"
  endpoint_address = "mk2monitor.mobiledevice.ph"
  endpoint_port = "51820"
  interface = "VPN->LC"
  persistent_keepalive = "10s"
}

resource "routeros_interface_wireguard_peer" "back_to_home_vpn_oppo_reno12_5g" {
  public_key = "K8wP4UxyNyTHYnSDZsjXHC2ygoU86VxNWN7T2b0LihQ="
  allowed_address = "192.168.216.3/32,fc00:0:0:216::3/128"
  interface = "back-to-home-vpn"
  persistent_keepalive = "30s"
  comment = "back-to-home-vpn OPPO Reno12 5G"
}

resource "routeros_interface_wireguard_peer" "back_to_home_vpn" {
  public_key = "MlTr2/ChSLfz9hIDGqEuAIh3hLO5T9xgurcAbosQ1lg="
  allowed_address = "192.168.216.2/32,fc00:0:0:216::2/128"
  interface = "back-to-home-vpn"
  persistent_keepalive = "5s"
  comment = "back-to-home-vpn"
}

resource "routeros_ip_ipsec_profile" "default" {
  name = "default"
  hash_algorithm = "sha1"
  enc_algorithm = "aes-128,3des"
  dh_group = "modp2048,modp1024"
  lifetime = "1d"
  proposal_check = "obey"
  nat_traversal = "True"
  dpd_interval = "8s"
  dpd_maximum_failures = "4"
  default = "True"
}

resource "routeros_ip_ipsec_proposal" "default" {
  name = "default"
  auth_algorithms = "sha1"
  enc_algorithms = "aes-256-cbc,aes-192-cbc,aes-128-cbc"
  lifetime = "30m"
  pfs_group = "modp1024"
  default = "True"
}

resource "routeros_ip_ipsec_policy" "_ffffff" {
  group = "default"
  src_address = "::/0"
  dst_address = "::/0"
  protocol = "all"
  proposal = "default"
  template = "True"
  default = "True"
}
