#!/bin/bash
# Generated by import_vpn_full.py

terraform import routeros_interface_sstp_client.vpn__cn '*F'
terraform import routeros_interface_sstp_client.vpn__emd '*E'
terraform import routeros_interface_sstp_client.vpn__jj '*D'
terraform import routeros_interface_sstp_client.vpn__z1 '*A'
terraform import routeros_interface_sstp_client.vpn_vx '*C'
terraform import routeros_interface_wireguard.vpn__lc '*25'
terraform import routeros_interface_wireguard.back_to_home_vpn '*21'
terraform import routeros_interface_wireguard_peer._7 '*7'
terraform import routeros_interface_wireguard_peer.back_to_home_vpn_oppo_reno12_5g '*8'
terraform import routeros_interface_wireguard_peer.back_to_home_vpn '*9'
terraform import routeros_ip_ipsec_profile.default '*A'
terraform import routeros_ip_ipsec_proposal.default '*0'
terraform import routeros_ip_ipsec_policy._ffffff '*FFFFFF'
