#!/bin/bash
# Generated by import_ospf.py

terraform import routeros_routing_ospf_instance.ospf_instance_1 '*0'
terraform import routeros_routing_ospf_area.backbone '*2'
terraform import routeros_routing_ospf_interface_template._1 '*1'
terraform import routeros_routing_ospf_interface_template._2 '*2'
terraform import routeros_routing_ospf_interface_template._3 '*3'
terraform import routeros_routing_ospf_interface_template._4 '*4'
terraform import routeros_routing_ospf_interface_template._5 '*5'
terraform import routeros_routing_ospf_interface_template._6 '*6'
