# Generated by import_ospf.py

resource "routeros_routing_ospf_instance" "ospf_instance_1" {
  name = "ospf-instance-1"
  version = "2"
  vrf = "main"
  router_id = "main"
  out_filter_chain = "ospf-out"
  originate_default = "never"
  in_filter_chain = "ospf-in"
}

resource "routeros_routing_ospf_area" "backbone" {
  name = "backbone"
  instance = "ospf-instance-1"
  area_id = "0.0.0.0"
  type = "default"
}

resource "routeros_routing_ospf_interface_template" "_1" {
  area = "backbone"
  interfaces = "*1B"
  type = "ptp"
  retransmit_interval = "5s"
  transmit_delay = "1s"
  hello_interval = "10s"
  dead_interval = "40s"
  priority = "128"
  cost = "1"
}

resource "routeros_routing_ospf_interface_template" "_2" {
  area = "backbone"
  interfaces = "*1C"
  type = "ptp"
  retransmit_interval = "5s"
  transmit_delay = "1s"
  hello_interval = "10s"
  dead_interval = "40s"
  priority = "128"
  cost = "1"
}

resource "routeros_routing_ospf_interface_template" "_3" {
  area = "backbone"
  interfaces = "*1D"
  type = "ptp"
  retransmit_interval = "5s"
  transmit_delay = "1s"
  hello_interval = "10s"
  dead_interval = "40s"
  priority = "128"
  cost = "1"
}

resource "routeros_routing_ospf_interface_template" "_4" {
  area = "backbone"
  interfaces = "*1E"
  type = "ptp"
  retransmit_interval = "5s"
  transmit_delay = "1s"
  hello_interval = "10s"
  dead_interval = "40s"
  priority = "128"
  cost = "1"
}

resource "routeros_routing_ospf_interface_template" "_5" {
  area = "backbone"
  interfaces = "*1F"
  type = "ptp"
  retransmit_interval = "5s"
  transmit_delay = "1s"
  hello_interval = "10s"
  dead_interval = "40s"
  priority = "128"
  cost = "1"
}

resource "routeros_routing_ospf_interface_template" "_6" {
  area = "backbone"
  interfaces = "*20"
  type = "ptp"
  retransmit_interval = "5s"
  transmit_delay = "1s"
  hello_interval = "10s"
  dead_interval = "40s"
  priority = "128"
  cost = "1"
}
