# Generated by import_routes_with_imports.py

resource "routeros_routing_table" "EDW" {
  name = "EDW"
  fib  = ""
}

resource "routeros_routing_table" "J_J" {
  name = "J&J"
  fib  = ""
}

resource "routeros_routing_table" "CN" {
  name = "CN"
  fib  = ""
}

resource "routeros_routing_table" "VX" {
  name = "VX"
  fib  = ""
}

resource "routeros_routing_table" "Z1" {
  name = "Z1"
  fib  = ""
}

resource "routeros_routing_table" "LC" {
  name = "LC"
  fib  = ""
}

resource "routeros_routing_table" "ISP1" {
  name = "ISP1"
  fib  = ""
}

resource "routeros_routing_table" "ISP2" {
  name = "ISP2"
  fib  = ""
}

resource "routeros_routing_rule" "rule_4" {
  action = "lookup"
  src_address = "192.168.11.0/24"
  dst_address = "192.168.65.0/24"
  table = "EDW"
  disabled = false
}

resource "routeros_routing_rule" "rule_10" {
  action = "lookup"
  src_address = "192.168.62.0/24"
  dst_address = "192.168.65.0/24"
  table = "EDW"
}

resource "routeros_ip_route" "r_0_0_0_0_0_10_0_0_6" {
  dst_address = "0.0.0.0/0"
  gateway = "10.0.0.6"
  distance = 1
  routing_table = "main"
  disabled = false
}

resource "routeros_ip_route" "r_0_0_0_0_0_10_0_0_2" {
  dst_address = "0.0.0.0/0"
  gateway = "10.0.0.2"
  distance = 1
  routing_table = "main"
  disabled = false
}

resource "routeros_ip_route" "r_0_0_0_0_0_10_0_0_4" {
  dst_address = "0.0.0.0/0"
  gateway = "10.0.0.4"
  distance = 1
  routing_table = "main"
  disabled = false
}

resource "routeros_ip_route" "r_0_0_0_0_0_VPN__LC" {
  dst_address = "0.0.0.0/0"
  gateway = "VPN->LC"
  distance = 3
  routing_table = "main"
  disabled = false
}

resource "routeros_ip_route" "r_192_168_65_100_32_VPN__JJ" {
  dst_address = "192.168.65.100/32"
  gateway = "VPN->JJ"
  distance = 1
  routing_table = "main"
  disabled = false
}

resource "routeros_ip_route" "r_192_168_99_0_24_10_0_0_4" {
  dst_address = "192.168.99.0/24"
  gateway = "10.0.0.4"
  distance = 1
  routing_table = "main"
  disabled = false
}

resource "routeros_ip_route" "r_0_0_0_0_0_10_0_0_10" {
  dst_address = "0.0.0.0/0"
  gateway = "10.0.0.10"
  distance = 1
  routing_table = "CN"
  disabled = false
}
